# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: "circleci/golang:1.12"

    working_directory: /go/src/github.com/mmmorris1975/aws-runas
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      # 'go get' only pulls from master branch, and circleci doesn't support dep
      - run: go get -v -t -d ./...
      - run: go vet -tests=false ./...
      - run: go test -v ./...
      - run: mkdir -p build
      - run: go build -v -ldflags '-X main.Version=0.0.1-0-circle' -o build/aws-runas

      - persist_to_workspace:
          root: build
          paths: aws-runas

  test:
    docker:
      - image: "circleci/ruby:2.6-stretch"

    steps:
      - checkout

      - attach_workspace:
          at: build

      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: mkdir -p /var/tmp/rspec
      - run:
          command: bundle exec rspec
          when: always

      - store_test_results:
          path: /var/tmp/rspec

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build